POST http://localhost:3006/products
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyIkX18iOnsiYWN0aXZlUGF0aHMiOnsicGF0aHMiOnsicGFzc3dvcmQiOiJpbml0IiwibmFtZSI6ImluaXQiLCJfaWQiOiJpbml0IiwiX192IjoiaW5pdCJ9LCJzdGF0ZXMiOnsicmVxdWlyZSI6e30sImluaXQiOnsiX2lkIjp0cnVlLCJuYW1lIjp0cnVlLCJwYXNzd29yZCI6dHJ1ZSwiX192Ijp0cnVlfX19LCJza2lwSWQiOnRydWV9LCIkaXNOZXciOmZhbHNlLCJfZG9jIjp7Il9pZCI6IjY2M2EzNTZlMzc5OGUzZmVmZjU2ZWQ5MCIsIm5hbWUiOiJhcm1hbiIsInBhc3N3b3JkIjoiJDJiJDEwJDJuSkkyMUNIUlNpZTJ4bW1YMnhXM2UuTm4waFpZMDdOMVpYVjZkalFvZHJ2TGhxcGNVSWJtIiwiX192IjowfSwiaWF0IjoxNzE1MDkwODc4LCJleHAiOjE3MTUxMDE2Nzh9.nhQFelBY1Pt1HcIgVMM3VXvHoZv8buRvkPbRcMVOYFk

{
  "name": "product 6",
  "description": "new product",
  "price": "100",
  "stock": "100"
}
#####